from dataclasses import dataclass
from typing import Sequence
import string

from evdev import ecodes as e

@dataclass
class KeyCodeInfo:
    keycode: int
    # Other keycodes that must be pressed with the keycode to send the key
    modifiers: Sequence[int] = ()

# Shared keys between all layouts
BASE_LAYOUT: dict[str, KeyCodeInfo] = {
    # Modifiers
    "alt_l": KeyCodeInfo(e.KEY_LEFTALT),
    "alt_r": KeyCodeInfo(e.KEY_RIGHTALT),
    "alt": KeyCodeInfo(e.KEY_LEFTALT),
    "ctrl_l": KeyCodeInfo(e.KEY_LEFTCTRL),
    "ctrl_r": KeyCodeInfo(e.KEY_RIGHTCTRL),
    "ctrl": KeyCodeInfo(e.KEY_LEFTCTRL),
    "control_l": KeyCodeInfo(e.KEY_LEFTCTRL),
    "control_r": KeyCodeInfo(e.KEY_RIGHTCTRL),
    "control": KeyCodeInfo(e.KEY_LEFTCTRL),
    "shift_l": KeyCodeInfo(e.KEY_LEFTSHIFT),
    "shift_r": KeyCodeInfo(e.KEY_RIGHTSHIFT),
    "shift": KeyCodeInfo(e.KEY_LEFTSHIFT),
    "super_l": KeyCodeInfo(e.KEY_LEFTMETA),
    "super_r": KeyCodeInfo(e.KEY_RIGHTMETA),
    "super": KeyCodeInfo(e.KEY_LEFTMETA),
    # Number row
    "`": KeyCodeInfo(e.KEY_GRAVE),
    "~": KeyCodeInfo(e.KEY_GRAVE, [e.KEY_LEFTSHIFT]),
    "1": KeyCodeInfo(e.KEY_1),
    "!": KeyCodeInfo(e.KEY_1, [e.KEY_LEFTSHIFT]),
    "2": KeyCodeInfo(e.KEY_2),
    "@": KeyCodeInfo(e.KEY_2, [e.KEY_LEFTSHIFT]),
    "3": KeyCodeInfo(e.KEY_3),
    "#": KeyCodeInfo(e.KEY_3, [e.KEY_LEFTSHIFT]),
    "4": KeyCodeInfo(e.KEY_4),
    "$": KeyCodeInfo(e.KEY_4, [e.KEY_LEFTSHIFT]),
    "5": KeyCodeInfo(e.KEY_5),
    "%": KeyCodeInfo(e.KEY_5, [e.KEY_LEFTSHIFT]),
    "6": KeyCodeInfo(e.KEY_6),
    "^": KeyCodeInfo(e.KEY_6, [e.KEY_LEFTSHIFT]),
    "7": KeyCodeInfo(e.KEY_7),
    "&": KeyCodeInfo(e.KEY_7, [e.KEY_LEFTSHIFT]),
    "8": KeyCodeInfo(e.KEY_8),
    "*": KeyCodeInfo(e.KEY_8, [e.KEY_LEFTSHIFT]),
    "9": KeyCodeInfo(e.KEY_9),
    "(": KeyCodeInfo(e.KEY_9, [e.KEY_LEFTSHIFT]),
    "0": KeyCodeInfo(e.KEY_0),
    ")": KeyCodeInfo(e.KEY_0, [e.KEY_LEFTSHIFT]),
    "-": KeyCodeInfo(e.KEY_MINUS),
    "_": KeyCodeInfo(e.KEY_MINUS, [e.KEY_LEFTSHIFT]),
    "=": KeyCodeInfo(e.KEY_EQUAL),
    "+": KeyCodeInfo(e.KEY_EQUAL, [e.KEY_LEFTSHIFT]),
    "\b": KeyCodeInfo(e.KEY_BACKSPACE),
    # Symbols
    " ": KeyCodeInfo(e.KEY_SPACE),
    "\n": KeyCodeInfo(e.KEY_ENTER),
    # https://github.com/openstenoproject/plover/blob/9b5a357f1fb57cb0a9a8596ae12cd1e84fcff6c4/plover/oslayer/osx/keyboardcontrol.py#L75
    # https://gist.github.com/jfortin42/68a1fcbf7738a1819eb4b2eef298f4f8

    "return": KeyCodeInfo(e.KEY_ENTER),
    "tab": KeyCodeInfo(e.KEY_TAB),
    "backspace": KeyCodeInfo(e.KEY_BACKSPACE),
    "delete": KeyCodeInfo(e.KEY_DELETE),
    "escape": KeyCodeInfo(e.KEY_ESC),
    "clear": KeyCodeInfo(e.KEY_CLEAR),
    # Navigation
    "up": KeyCodeInfo(e.KEY_UP),
    "down": KeyCodeInfo(e.KEY_DOWN),
    "left": KeyCodeInfo(e.KEY_LEFT),
    "right": KeyCodeInfo(e.KEY_RIGHT),
    "page_up": KeyCodeInfo(e.KEY_PAGEUP),
    "page_down": KeyCodeInfo(e.KEY_PAGEDOWN),
    "home": KeyCodeInfo(e.KEY_HOME),
    "insert": KeyCodeInfo(e.KEY_INSERT),
    "end": KeyCodeInfo(e.KEY_END),
    "space": KeyCodeInfo(e.KEY_SPACE),
    "print": KeyCodeInfo(e.KEY_PRINT),
    # Function keys
    "fn": KeyCodeInfo(e.KEY_FN),
    "f1": KeyCodeInfo(e.KEY_F1),
    "f2": KeyCodeInfo(e.KEY_F2),
    "f3": KeyCodeInfo(e.KEY_F3),
    "f4": KeyCodeInfo(e.KEY_F4),
    "f5": KeyCodeInfo(e.KEY_F5),
    "f6": KeyCodeInfo(e.KEY_F6),
    "f7": KeyCodeInfo(e.KEY_F7),
    "f8": KeyCodeInfo(e.KEY_F8),
    "f9": KeyCodeInfo(e.KEY_F9),
    "f10": KeyCodeInfo(e.KEY_F10),
    "f11": KeyCodeInfo(e.KEY_F11),
    "f12": KeyCodeInfo(e.KEY_F12),
    "f13": KeyCodeInfo(e.KEY_F13),
    "f14": KeyCodeInfo(e.KEY_F14),
    "f15": KeyCodeInfo(e.KEY_F15),
    "f16": KeyCodeInfo(e.KEY_F16),
    "f17": KeyCodeInfo(e.KEY_F17),
    "f18": KeyCodeInfo(e.KEY_F18),
    "f19": KeyCodeInfo(e.KEY_F19),
    "f20": KeyCodeInfo(e.KEY_F20),
    "f21": KeyCodeInfo(e.KEY_F21),
    "f22": KeyCodeInfo(e.KEY_F22),
    "f23": KeyCodeInfo(e.KEY_F23),
    "f24": KeyCodeInfo(e.KEY_F24),
    # Numpad
    "kp_1": KeyCodeInfo(e.KEY_KP1),
    "kp_2": KeyCodeInfo(e.KEY_KP2),
    "kp_3": KeyCodeInfo(e.KEY_KP3),
    "kp_4": KeyCodeInfo(e.KEY_KP4),
    "kp_5": KeyCodeInfo(e.KEY_KP5),
    "kp_6": KeyCodeInfo(e.KEY_KP6),
    "kp_7": KeyCodeInfo(e.KEY_KP7),
    "kp_8": KeyCodeInfo(e.KEY_KP8),
    "kp_9": KeyCodeInfo(e.KEY_KP9),
    "kp_0": KeyCodeInfo(e.KEY_KP0),
    "kp_add": KeyCodeInfo(e.KEY_KPPLUS),
    "kp_decimal": KeyCodeInfo(e.KEY_KPDOT),
    "kp_delete": KeyCodeInfo(e.KEY_DELETE),  # There is no KPDELETE
    "kp_divide": KeyCodeInfo(e.KEY_KPSLASH),
    "kp_enter": KeyCodeInfo(e.KEY_KPENTER),
    "kp_equal": KeyCodeInfo(e.KEY_KPEQUAL),
    "kp_multiply": KeyCodeInfo(e.KEY_KPASTERISK),
    "kp_subtract": KeyCodeInfo(e.KEY_KPMINUS),
    # Media keys
    "audioraisevolume": KeyCodeInfo(e.KEY_VOLUMEUP),
    "audiolowervolume": KeyCodeInfo(e.KEY_VOLUMEDOWN),
    "monbrightnessup": KeyCodeInfo(e.KEY_BRIGHTNESSUP),
    "monbrightnessdown": KeyCodeInfo(e.KEY_BRIGHTNESSDOWN),
    "audiomute": KeyCodeInfo(e.KEY_MUTE),
    "num_lock": KeyCodeInfo(e.KEY_NUMLOCK),
    "eject": KeyCodeInfo(e.KEY_EJECTCD),
    "audiopause": KeyCodeInfo(e.KEY_PAUSE),
    "audionext": KeyCodeInfo(e.KEY_NEXT),
    "audioplay": KeyCodeInfo(e.KEY_PLAY),
    "audiorewind": KeyCodeInfo(e.KEY_REWIND),
    "kbdbrightnessup": KeyCodeInfo(e.KEY_KBDILLUMUP),
    "kbdbrightnessdown": KeyCodeInfo(e.KEY_KBDILLUMDOWN),
}

MODIFIER_KEY_CODES: set[int] = {
    e.KEY_LEFTSHIFT, e.KEY_RIGHTSHIFT,
    e.KEY_LEFTCTRL, e.KEY_RIGHTCTRL,
    e.KEY_LEFTALT, e.KEY_RIGHTALT,
    e.KEY_LEFTMETA, e.KEY_RIGHTMETA,
}

DEFAULT_LAYOUT = "qwerty"
LAYOUTS = {
    # Only specify keys that differ from qwerty
    "qwerty": {
        **BASE_LAYOUT,
        # First row
        "q": KeyCodeInfo(e.KEY_Q),
        "Q": KeyCodeInfo(e.KEY_Q, [e.KEY_LEFTSHIFT]),
        "w": KeyCodeInfo(e.KEY_W),
        "W": KeyCodeInfo(e.KEY_W, [e.KEY_LEFTSHIFT]),
        "e": KeyCodeInfo(e.KEY_E),
        "E": KeyCodeInfo(e.KEY_E, [e.KEY_LEFTSHIFT]),
        "r": KeyCodeInfo(e.KEY_R),
        "R": KeyCodeInfo(e.KEY_R, [e.KEY_LEFTSHIFT]),
        "t": KeyCodeInfo(e.KEY_T),
        "T": KeyCodeInfo(e.KEY_T, [e.KEY_LEFTSHIFT]),
        "y": KeyCodeInfo(e.KEY_Y),
        "Y": KeyCodeInfo(e.KEY_Y, [e.KEY_LEFTSHIFT]),
        "u": KeyCodeInfo(e.KEY_U),
        "U": KeyCodeInfo(e.KEY_U, [e.KEY_LEFTSHIFT]),
        "i": KeyCodeInfo(e.KEY_I),
        "I": KeyCodeInfo(e.KEY_I, [e.KEY_LEFTSHIFT]),
        "o": KeyCodeInfo(e.KEY_O),
        "O": KeyCodeInfo(e.KEY_O, [e.KEY_LEFTSHIFT]),
        "p": KeyCodeInfo(e.KEY_P),
        "P": KeyCodeInfo(e.KEY_P, [e.KEY_LEFTSHIFT]),
        "[": KeyCodeInfo(e.KEY_LEFTBRACE),
        "{": KeyCodeInfo(e.KEY_LEFTBRACE, [e.KEY_LEFTSHIFT]),
        "]": KeyCodeInfo(e.KEY_RIGHTBRACE),
        "}": KeyCodeInfo(e.KEY_RIGHTBRACE, [e.KEY_LEFTSHIFT]),
        "\\": KeyCodeInfo(e.KEY_BACKSLASH),
        "|": KeyCodeInfo(e.KEY_BACKSLASH, [e.KEY_LEFTSHIFT]),
        # Second row
        "a": KeyCodeInfo(e.KEY_A),
        "A": KeyCodeInfo(e.KEY_A, [e.KEY_LEFTSHIFT]),
        "s": KeyCodeInfo(e.KEY_S),
        "S": KeyCodeInfo(e.KEY_S, [e.KEY_LEFTSHIFT]),
        "d": KeyCodeInfo(e.KEY_D),
        "D": KeyCodeInfo(e.KEY_D, [e.KEY_LEFTSHIFT]),
        "f": KeyCodeInfo(e.KEY_F),
        "F": KeyCodeInfo(e.KEY_F, [e.KEY_LEFTSHIFT]),
        "g": KeyCodeInfo(e.KEY_G),
        "G": KeyCodeInfo(e.KEY_G, [e.KEY_LEFTSHIFT]),
        "h": KeyCodeInfo(e.KEY_H),
        "H": KeyCodeInfo(e.KEY_H, [e.KEY_LEFTSHIFT]),
        "j": KeyCodeInfo(e.KEY_J),
        "J": KeyCodeInfo(e.KEY_J, [e.KEY_LEFTSHIFT]),
        "k": KeyCodeInfo(e.KEY_K),
        "K": KeyCodeInfo(e.KEY_K, [e.KEY_LEFTSHIFT]),
        "l": KeyCodeInfo(e.KEY_L),
        "L": KeyCodeInfo(e.KEY_L, [e.KEY_LEFTSHIFT]),
        ";": KeyCodeInfo(e.KEY_SEMICOLON),
        ":": KeyCodeInfo(e.KEY_SEMICOLON, [e.KEY_LEFTSHIFT]),
        "'": KeyCodeInfo(e.KEY_APOSTROPHE),
        "\"": KeyCodeInfo(e.KEY_APOSTROPHE, [e.KEY_LEFTSHIFT]),
        # Third row
        "z": KeyCodeInfo(e.KEY_Z),
        "Z": KeyCodeInfo(e.KEY_Z, [e.KEY_LEFTSHIFT]),
        "x": KeyCodeInfo(e.KEY_X),
        "X": KeyCodeInfo(e.KEY_X, [e.KEY_LEFTSHIFT]),
        "c": KeyCodeInfo(e.KEY_C),
        "C": KeyCodeInfo(e.KEY_C, [e.KEY_LEFTSHIFT]),
        "v": KeyCodeInfo(e.KEY_V),
        "V": KeyCodeInfo(e.KEY_V, [e.KEY_LEFTSHIFT]),
        "b": KeyCodeInfo(e.KEY_B),
        "B": KeyCodeInfo(e.KEY_B, [e.KEY_LEFTSHIFT]),
        "n": KeyCodeInfo(e.KEY_N),
        "N": KeyCodeInfo(e.KEY_N, [e.KEY_LEFTSHIFT]),
        "m": KeyCodeInfo(e.KEY_M),
        "M": KeyCodeInfo(e.KEY_M, [e.KEY_LEFTSHIFT]),
        ",": KeyCodeInfo(e.KEY_COMMA),
        "<": KeyCodeInfo(e.KEY_COMMA, [e.KEY_LEFTSHIFT]),
        ".": KeyCodeInfo(e.KEY_DOT),
        ">": KeyCodeInfo(e.KEY_DOT, [e.KEY_LEFTSHIFT]),
        "/": KeyCodeInfo(e.KEY_SLASH),
        "?": KeyCodeInfo(e.KEY_SLASH, [e.KEY_LEFTSHIFT]),
    },
    "qwertz": {
        **BASE_LAYOUT,
        # Number row
        "°": KeyCodeInfo(e.KEY_GRAVE, [e.KEY_LEFTSHIFT]),
        "1": KeyCodeInfo(e.KEY_1),
        "!": KeyCodeInfo(e.KEY_1, [e.KEY_LEFTSHIFT]),
        "2": KeyCodeInfo(e.KEY_2),
        "\"": KeyCodeInfo(e.KEY_2, [e.KEY_LEFTSHIFT]),
        "3": KeyCodeInfo(e.KEY_3),
        "§": KeyCodeInfo(e.KEY_3, [e.KEY_LEFTSHIFT]),
        "4": KeyCodeInfo(e.KEY_4),
        "$": KeyCodeInfo(e.KEY_4, [e.KEY_LEFTSHIFT]),
        "5": KeyCodeInfo(e.KEY_5),
        "%": KeyCodeInfo(e.KEY_5, [e.KEY_LEFTSHIFT]),
        "6": KeyCodeInfo(e.KEY_6),
        "&": KeyCodeInfo(e.KEY_6, [e.KEY_LEFTSHIFT]),
        "7": KeyCodeInfo(e.KEY_7),
        "/": KeyCodeInfo(e.KEY_7, [e.KEY_LEFTSHIFT]),
        "8": KeyCodeInfo(e.KEY_8),
        "(": KeyCodeInfo(e.KEY_8, [e.KEY_LEFTSHIFT]),
        "9": KeyCodeInfo(e.KEY_9),
        ")": KeyCodeInfo(e.KEY_9, [e.KEY_LEFTSHIFT]),
        "0": KeyCodeInfo(e.KEY_0),
        "=": KeyCodeInfo(e.KEY_0, [e.KEY_LEFTSHIFT]),
        "ß": KeyCodeInfo(e.KEY_MINUS),
        "?": KeyCodeInfo(e.KEY_MINUS, [e.KEY_LEFTSHIFT]),
        "`": KeyCodeInfo(e.KEY_EQUAL, [e.KEY_LEFTSHIFT]),
        "\b": KeyCodeInfo(e.KEY_BACKSPACE),
        # Top row
        "q": KeyCodeInfo(e.KEY_Q),
        "Q": KeyCodeInfo(e.KEY_Q, [e.KEY_LEFTSHIFT]),
        "w": KeyCodeInfo(e.KEY_W),
        "W": KeyCodeInfo(e.KEY_W, [e.KEY_LEFTSHIFT]),
        "e": KeyCodeInfo(e.KEY_E),
        "E": KeyCodeInfo(e.KEY_E, [e.KEY_LEFTSHIFT]),
        "r": KeyCodeInfo(e.KEY_R),
        "R": KeyCodeInfo(e.KEY_R, [e.KEY_LEFTSHIFT]),
        "t": KeyCodeInfo(e.KEY_T),
        "T": KeyCodeInfo(e.KEY_T, [e.KEY_LEFTSHIFT]),
        "z": KeyCodeInfo(e.KEY_Y),
        "Z": KeyCodeInfo(e.KEY_Y, [e.KEY_LEFTSHIFT]),
        "u": KeyCodeInfo(e.KEY_U),
        "U": KeyCodeInfo(e.KEY_U, [e.KEY_LEFTSHIFT]),
        "i": KeyCodeInfo(e.KEY_I),
        "I": KeyCodeInfo(e.KEY_I, [e.KEY_LEFTSHIFT]),
        "o": KeyCodeInfo(e.KEY_O),
        "O": KeyCodeInfo(e.KEY_O, [e.KEY_LEFTSHIFT]),
        "p": KeyCodeInfo(e.KEY_P),
        "P": KeyCodeInfo(e.KEY_P, [e.KEY_LEFTSHIFT]),
        "ü": KeyCodeInfo(e.KEY_LEFTBRACE),
        "Ü": KeyCodeInfo(e.KEY_LEFTBRACE, [e.KEY_LEFTSHIFT]),
        "+": KeyCodeInfo(e.KEY_RIGHTBRACE),
        "*": KeyCodeInfo(e.KEY_RIGHTBRACE, [e.KEY_LEFTSHIFT]),
        "#": KeyCodeInfo(e.KEY_BACKSLASH),
        "'": KeyCodeInfo(e.KEY_BACKSLASH, [e.KEY_LEFTSHIFT]),
        # Middle row
        "a": KeyCodeInfo(e.KEY_A),
        "A": KeyCodeInfo(e.KEY_A, [e.KEY_LEFTSHIFT]),
        "s": KeyCodeInfo(e.KEY_S),
        "S": KeyCodeInfo(e.KEY_S, [e.KEY_LEFTSHIFT]),
        "d": KeyCodeInfo(e.KEY_D),
        "D": KeyCodeInfo(e.KEY_D, [e.KEY_LEFTSHIFT]),
        "f": KeyCodeInfo(e.KEY_F),
        "F": KeyCodeInfo(e.KEY_F, [e.KEY_LEFTSHIFT]),
        "g": KeyCodeInfo(e.KEY_G),
        "G": KeyCodeInfo(e.KEY_G, [e.KEY_LEFTSHIFT]),
        "h": KeyCodeInfo(e.KEY_H),
        "H": KeyCodeInfo(e.KEY_H, [e.KEY_LEFTSHIFT]),
        "j": KeyCodeInfo(e.KEY_J),
        "J": KeyCodeInfo(e.KEY_J, [e.KEY_LEFTSHIFT]),
        "k": KeyCodeInfo(e.KEY_K),
        "K": KeyCodeInfo(e.KEY_K, [e.KEY_LEFTSHIFT]),
        "l": KeyCodeInfo(e.KEY_L),
        "L": KeyCodeInfo(e.KEY_L, [e.KEY_LEFTSHIFT]),
        "ö": KeyCodeInfo(e.KEY_SEMICOLON),
        "Ö": KeyCodeInfo(e.KEY_SEMICOLON, [e.KEY_LEFTSHIFT]),
        "ä": KeyCodeInfo(e.KEY_APOSTROPHE),
        "Ä": KeyCodeInfo(e.KEY_APOSTROPHE),
        # Bottom row
        "y": KeyCodeInfo(e.KEY_Z),
        "Y": KeyCodeInfo(e.KEY_Z, [e.KEY_LEFTSHIFT]),
        "x": KeyCodeInfo(e.KEY_X),
        "X": KeyCodeInfo(e.KEY_X, [e.KEY_LEFTSHIFT]),
        "c": KeyCodeInfo(e.KEY_C),
        "C": KeyCodeInfo(e.KEY_C, [e.KEY_LEFTSHIFT]),
        "v": KeyCodeInfo(e.KEY_V),
        "V": KeyCodeInfo(e.KEY_V, [e.KEY_LEFTSHIFT]),
        "b": KeyCodeInfo(e.KEY_B),
        "B": KeyCodeInfo(e.KEY_B, [e.KEY_LEFTSHIFT]),
        "n": KeyCodeInfo(e.KEY_N),
        "N": KeyCodeInfo(e.KEY_N, [e.KEY_LEFTSHIFT]),
        "m": KeyCodeInfo(e.KEY_M),
        "M": KeyCodeInfo(e.KEY_M, [e.KEY_LEFTSHIFT]),
        ",": KeyCodeInfo(e.KEY_COMMA),
        "<": KeyCodeInfo(e.KEY_COMMA, [e.KEY_LEFTSHIFT]),
        ".": KeyCodeInfo(e.KEY_DOT),
        ">": KeyCodeInfo(e.KEY_DOT, [e.KEY_LEFTSHIFT]),
        "-": KeyCodeInfo(e.KEY_SLASH),
        "_": KeyCodeInfo(e.KEY_SLASH, [e.KEY_LEFTSHIFT]),
    },
    "colemak": {
        **BASE_LAYOUT,
        # Top row
        "q": KeyCodeInfo(e.KEY_Q),
        "Q": KeyCodeInfo(e.KEY_Q, [e.KEY_LEFTSHIFT]),
        "w": KeyCodeInfo(e.KEY_W),
        "W": KeyCodeInfo(e.KEY_W, [e.KEY_LEFTSHIFT]),
        "f": KeyCodeInfo(e.KEY_E),
        "F": KeyCodeInfo(e.KEY_E, [e.KEY_LEFTSHIFT]),
        "p": KeyCodeInfo(e.KEY_R),
        "P": KeyCodeInfo(e.KEY_R, [e.KEY_LEFTSHIFT]),
        "g": KeyCodeInfo(e.KEY_T),
        "G": KeyCodeInfo(e.KEY_T, [e.KEY_LEFTSHIFT]),
        "j": KeyCodeInfo(e.KEY_Y),
        "J": KeyCodeInfo(e.KEY_Y, [e.KEY_LEFTSHIFT]),
        "l": KeyCodeInfo(e.KEY_U),
        "L": KeyCodeInfo(e.KEY_U, [e.KEY_LEFTSHIFT]),
        "u": KeyCodeInfo(e.KEY_I),
        "U": KeyCodeInfo(e.KEY_I, [e.KEY_LEFTSHIFT]),
        "y": KeyCodeInfo(e.KEY_O),
        "Y": KeyCodeInfo(e.KEY_O, [e.KEY_LEFTSHIFT]),
        ";": KeyCodeInfo(e.KEY_O),
        ":": KeyCodeInfo(e.KEY_O, [e.KEY_LEFTSHIFT]),
        "[": KeyCodeInfo(e.KEY_LEFTBRACE),
        "{": KeyCodeInfo(e.KEY_LEFTBRACE, [e.KEY_LEFTSHIFT]),
        "]": KeyCodeInfo(e.KEY_RIGHTBRACE),
        "}": KeyCodeInfo(e.KEY_RIGHTBRACE, [e.KEY_LEFTSHIFT]),
        "\\": KeyCodeInfo(e.KEY_BACKSLASH),
        "|": KeyCodeInfo(e.KEY_BACKSLASH, [e.KEY_LEFTSHIFT]),
        # Middle row
        "a": KeyCodeInfo(e.KEY_A),
        "A": KeyCodeInfo(e.KEY_A, [e.KEY_LEFTSHIFT]),
        "r": KeyCodeInfo(e.KEY_S),
        "R": KeyCodeInfo(e.KEY_S, [e.KEY_LEFTSHIFT]),
        "s": KeyCodeInfo(e.KEY_D),
        "S": KeyCodeInfo(e.KEY_D, [e.KEY_LEFTSHIFT]),
        "t": KeyCodeInfo(e.KEY_F),
        "T": KeyCodeInfo(e.KEY_F, [e.KEY_LEFTSHIFT]),
        "d": KeyCodeInfo(e.KEY_G),
        "D": KeyCodeInfo(e.KEY_G, [e.KEY_LEFTSHIFT]),
        "h": KeyCodeInfo(e.KEY_H),
        "H": KeyCodeInfo(e.KEY_H, [e.KEY_LEFTSHIFT]),
        "n": KeyCodeInfo(e.KEY_J),
        "N": KeyCodeInfo(e.KEY_J, [e.KEY_LEFTSHIFT]),
        "e": KeyCodeInfo(e.KEY_K),
        "E": KeyCodeInfo(e.KEY_K, [e.KEY_LEFTSHIFT]),
        "i": KeyCodeInfo(e.KEY_L),
        "I": KeyCodeInfo(e.KEY_L, [e.KEY_LEFTSHIFT]),
        "o": KeyCodeInfo(e.KEY_SEMICOLON),
        "O": KeyCodeInfo(e.KEY_SEMICOLON, [e.KEY_LEFTSHIFT]),
        "'": KeyCodeInfo(e.KEY_APOSTROPHE),
        "\"": KeyCodeInfo(e.KEY_APOSTROPHE, [e.KEY_LEFTSHIFT]),
        # Bottom row
        "z": KeyCodeInfo(e.KEY_Z),
        "Z": KeyCodeInfo(e.KEY_Z, [e.KEY_LEFTSHIFT]),
        "x": KeyCodeInfo(e.KEY_X),
        "X": KeyCodeInfo(e.KEY_X, [e.KEY_LEFTSHIFT]),
        "c": KeyCodeInfo(e.KEY_C),
        "C": KeyCodeInfo(e.KEY_C, [e.KEY_LEFTSHIFT]),
        "v": KeyCodeInfo(e.KEY_V),
        "V": KeyCodeInfo(e.KEY_V, [e.KEY_LEFTSHIFT]),
        "b": KeyCodeInfo(e.KEY_B),
        "B": KeyCodeInfo(e.KEY_B, [e.KEY_LEFTSHIFT]),
        "k": KeyCodeInfo(e.KEY_N),
        "K": KeyCodeInfo(e.KEY_N, [e.KEY_LEFTSHIFT]),
        "m": KeyCodeInfo(e.KEY_M),
        "M": KeyCodeInfo(e.KEY_M, [e.KEY_LEFTSHIFT]),
        ",": KeyCodeInfo(e.KEY_COMMA),
        "<": KeyCodeInfo(e.KEY_COMMA, [e.KEY_LEFTSHIFT]),
        ".": KeyCodeInfo(e.KEY_DOT),
        ">": KeyCodeInfo(e.KEY_DOT, [e.KEY_LEFTSHIFT]),
        "/": KeyCodeInfo(e.KEY_SLASH),
        "?": KeyCodeInfo(e.KEY_SLASH, [e.KEY_LEFTSHIFT]),
    },
    "colemak-dh": {
        **BASE_LAYOUT,
        # Top row
        "q": KeyCodeInfo(e.KEY_Q),
        "Q": KeyCodeInfo(e.KEY_Q, [e.KEY_LEFTSHIFT]),
        "w": KeyCodeInfo(e.KEY_W),
        "W": KeyCodeInfo(e.KEY_W, [e.KEY_LEFTSHIFT]),
        "f": KeyCodeInfo(e.KEY_E),
        "F": KeyCodeInfo(e.KEY_E, [e.KEY_LEFTSHIFT]),
        "p": KeyCodeInfo(e.KEY_R),
        "P": KeyCodeInfo(e.KEY_R, [e.KEY_LEFTSHIFT]),
        "b": KeyCodeInfo(e.KEY_T),
        "B": KeyCodeInfo(e.KEY_T, [e.KEY_LEFTSHIFT]),
        "j": KeyCodeInfo(e.KEY_Y),
        "J": KeyCodeInfo(e.KEY_Y, [e.KEY_LEFTSHIFT]),
        "l": KeyCodeInfo(e.KEY_U),
        "L": KeyCodeInfo(e.KEY_U, [e.KEY_LEFTSHIFT]),
        "u": KeyCodeInfo(e.KEY_I),
        "U": KeyCodeInfo(e.KEY_I, [e.KEY_LEFTSHIFT]),
        "y": KeyCodeInfo(e.KEY_O),
        "Y": KeyCodeInfo(e.KEY_O, [e.KEY_LEFTSHIFT]),
        ";": KeyCodeInfo(e.KEY_P),
        ":": KeyCodeInfo(e.KEY_P, [e.KEY_LEFTSHIFT]),
        "[": KeyCodeInfo(e.KEY_LEFTBRACE),
        "{": KeyCodeInfo(e.KEY_LEFTBRACE, [e.KEY_LEFTSHIFT]),
        "]": KeyCodeInfo(e.KEY_RIGHTBRACE),
        "}": KeyCodeInfo(e.KEY_RIGHTBRACE, [e.KEY_LEFTSHIFT]),
        "\\": KeyCodeInfo(e.KEY_BACKSLASH),
        "|": KeyCodeInfo(e.KEY_BACKSLASH, [e.KEY_LEFTSHIFT]),
        # Middle row
        "a": KeyCodeInfo(e.KEY_A),
        "A": KeyCodeInfo(e.KEY_A, [e.KEY_LEFTSHIFT]),
        "r": KeyCodeInfo(e.KEY_S),
        "R": KeyCodeInfo(e.KEY_S, [e.KEY_LEFTSHIFT]),
        "s": KeyCodeInfo(e.KEY_D),
        "S": KeyCodeInfo(e.KEY_D, [e.KEY_LEFTSHIFT]),
        "t": KeyCodeInfo(e.KEY_F),
        "T": KeyCodeInfo(e.KEY_F, [e.KEY_LEFTSHIFT]),
        "g": KeyCodeInfo(e.KEY_G),
        "G": KeyCodeInfo(e.KEY_G, [e.KEY_LEFTSHIFT]),
        "m": KeyCodeInfo(e.KEY_H),
        "M": KeyCodeInfo(e.KEY_H, [e.KEY_LEFTSHIFT]),
        "n": KeyCodeInfo(e.KEY_J),
        "N": KeyCodeInfo(e.KEY_J, [e.KEY_LEFTSHIFT]),
        "e": KeyCodeInfo(e.KEY_K),
        "E": KeyCodeInfo(e.KEY_K, [e.KEY_LEFTSHIFT]),
        "i": KeyCodeInfo(e.KEY_L),
        "I": KeyCodeInfo(e.KEY_L, [e.KEY_LEFTSHIFT]),
        "o": KeyCodeInfo(e.KEY_SEMICOLON),
        "O": KeyCodeInfo(e.KEY_SEMICOLON, [e.KEY_LEFTSHIFT]),
        "'": KeyCodeInfo(e.KEY_APOSTROPHE),
        "\"": KeyCodeInfo(e.KEY_APOSTROPHE, [e.KEY_LEFTSHIFT]),
        # Bottom row
        "x": KeyCodeInfo(e.KEY_Z),
        "X": KeyCodeInfo(e.KEY_Z, [e.KEY_LEFTSHIFT]),
        "c": KeyCodeInfo(e.KEY_X),
        "C": KeyCodeInfo(e.KEY_X, [e.KEY_LEFTSHIFT]),
        "d": KeyCodeInfo(e.KEY_C),
        "D": KeyCodeInfo(e.KEY_C, [e.KEY_LEFTSHIFT]),
        "v": KeyCodeInfo(e.KEY_V),
        "V": KeyCodeInfo(e.KEY_V, [e.KEY_LEFTSHIFT]),
        "z": KeyCodeInfo(e.KEY_B),  # less than-key
        "Z": KeyCodeInfo(e.KEY_B, [e.KEY_LEFTSHIFT]),
        "k": KeyCodeInfo(e.KEY_N),
        "K": KeyCodeInfo(e.KEY_N, [e.KEY_LEFTSHIFT]),
        "h": KeyCodeInfo(e.KEY_M),
        "H": KeyCodeInfo(e.KEY_M, [e.KEY_LEFTSHIFT]),
        ",": KeyCodeInfo(e.KEY_COMMA),
        "<": KeyCodeInfo(e.KEY_COMMA, [e.KEY_LEFTSHIFT]),
        ".": KeyCodeInfo(e.KEY_DOT),
        ">": KeyCodeInfo(e.KEY_DOT, [e.KEY_LEFTSHIFT]),
        "/": KeyCodeInfo(e.KEY_SLASH),
        "?": KeyCodeInfo(e.KEY_SLASH, [e.KEY_LEFTSHIFT]),
    },
}

# Verify that no modifier has its own modifiers
for layout_name, layout in LAYOUTS.items():
    for key, key_info in layout.items():
        if key_info.keycode in MODIFIER_KEY_CODES:
            assert len(key_info.modifiers) == 0, f"Modifier {key_info.keycode} in layout {layout_name} should not itself have modifiers"

WAYLAND_AUTO_LAYOUT_NAME = "wayland-auto"

# Additional aliases for xkbcommon keysyms
# Keys beginning with "XF86" are handled as a special case during xkbcommon keymap processing
# For each xkbcommon keysyms, the lowercase of the symbol name is also added to the keymap by the code
XKB_KEY_NAME_TO_ALIASES: dict[str, list[str]] = {
    "Return": ["\n"],
    "Control_L": ["ctrl"],
    "Shift_L": ["shift"],
    "Super_L": ["super", "windows", "command"],
    "Alt_L": ["alt", "option"],
    "Tab": ["\t"],
    "Next": ["page_down"],
    "Prior": ["page_up"],
    "KP_Home": ["kp_7"],
    "KP_Up": ["kp_8"],
    "KP_Prior": ["kp_9"],
    "KP_Left": ["kp_4"],
    "KP_Begin": ["kp_5"],
    "KP_Right": ["kp_6"],
    "KP_End": ["kp_1"],
    "KP_Down": ["kp_2"],
    "KP_Next": ["kp_3"],
    "KP_Insert": ["kp_0"],
    "KP_Delete": ["kp_dot", "kp_decimal"],
}

# Ignore keys with modifiers
HANDLED_KEYCODE_TO_KEY = {v.keycode: key for key, v in LAYOUTS[DEFAULT_LAYOUT].items() if len(v.modifiers) == 0}
# Make sure no keys missing. Last 5 are "\t\n\r\x0b\x0c" which don't need to be handled
assert all(c in LAYOUTS[DEFAULT_LAYOUT].keys() for c in string.printable[:-5])
